#!/usr/bin/env python

""" VictoriaMetrics cli tool. """

import argparse
from cmd import Cmd
import json
from json.decoder import JSONDecodeError
import re
from urllib.error import URLError
from urllib.parse import urlencode
from urllib.request import Request, urlopen
import sys


class VmCli(Cmd):
    """ CLI tool to deal with VictoriaMetrics DB. """

    VERSION = '0.0.1'
    intro = 'CLI tool to deal with VictoriaMetrics DB (type help or ?).'
    prompt = '> '
    vm_host = '127.0.0.1'
    vm_port = 8428
    vm_timeout = 4.0

    @property
    def vm_base_url(self):
        """VictoriaMetrics base URL for all requests"""
        return f'http://{self.vm_host}:{self.vm_port}'

    def emptyline(self) -> bool:
        """Avoid empty line execute again the last command"""
        return

    # def precmd(self, line: str) -> str:
    #     """Allow comment in cli"""
    #     if '#' in line:
    #         line = line.split('#')[0]
    #     return line

    def do_add(self, args: str = ''):
        """Add a metric value"""
        # process command args: "add metric value [timestamp_ms]"
        args_l = args.split()
        try:
            # mandatory args
            # metric name
            metric = args_l[0].strip()
            # allow promethus metric name, disallow double underscore as first chars
            if not re.match(r'^(?!.*__.*)[a-zA-Z_:][a-zA-Z0-9_:]*', metric):
                print('bad metric name (a good one could be my_metric{tag="foo"})')
                return
            # value
            try:
                value  = float(args_l[1].strip())
            except ValueError:
                print('bad metric value (a good one could be 42.0)')
                return
            # timestamp (in ms): it's an optional arg
            try:
                timestamp_ms  = int(args_l[2].strip())
            except IndexError:
                timestamp_ms = ''
            except (TypeError, ValueError):
                print('bad timestamp (a good one could be 1702289355551)')
                return
        except IndexError:
            print('error: bad invocation (a good one is "add metric value [timestamp_ms]")')
            return
        # format publication message as a compact json message
        pub_msg = f'{metric} {value}'
        if timestamp_ms:
            pub_msg += f' {timestamp_ms}'
        # post message to VictoriaMerctrics
        try:
            query_url = f'{self.vm_base_url}/api/v1/import/prometheus'
            with urlopen(Request(query_url, data=pub_msg.encode()), timeout=self.vm_timeout) as resp:
                if resp.status == 204:
                    print(f'DEBUG publish {pub_msg=}')
                    print(f'import {len(pub_msg)} bytes OK')
        except URLError as e:
            print(f'error: {e!r}')

    def do_del(self, arg: str = ''):
        """Delete a metric"""
        try:
            query_prm = urlencode({'match[]': arg})
            query_url = f'{self.vm_base_url}/api/v1/admin/tsdb/delete_series?{query_prm}'
            with urlopen(query_url, timeout=self.vm_timeout) as resp:
                if resp.status == 204:
                    print('delete OK')
        except (JSONDecodeError, URLError) as e:
            print(f'error: {e}')

    def do_list(self, _arg):
        """List all available metrics"""
        try:
            query_prm = urlencode({'start': '-3y'})
            query_url = f'{self.vm_base_url}/api/v1/label/__name__/values?{query_prm}'
            with urlopen(query_url, timeout=self.vm_timeout) as resp:
                js_d = json.loads(resp.read())
                if js_d.get('status', '') == 'success':
                    for metric in js_d.get('data', []):
                        print(metric)
        except (JSONDecodeError, URLError) as e:
            print(f'error: {e}')

    def do_version(self, _arg):
        """Print vm-cli version"""
        print(f'vm-cli {self.VERSION}')

    def do_exit(self, _arg):
        """Exit from cli"""
        return True


if __name__ == '__main__':
    # init
    vm_cli = VmCli()
    # parse command line args
    parser = argparse.ArgumentParser()
    parser.add_argument('-H', '--host', type=str, default=vm_cli.vm_host,
                        help=f'Host (default: "{vm_cli.vm_host}")')
    parser.add_argument('-p', '--port', type=int, default=vm_cli.vm_port,
                        help=f'TCP port (default: {vm_cli.vm_port})')
    parser.add_argument('-t', '--timeout', type=float, default=vm_cli.vm_timeout,
                        help=f'socket timeout (default: {vm_cli.vm_timeout})')
    parser.add_argument('command', nargs='*', default='',
                        help='vm-cli command to execute')
    args = parser.parse_args()
    # apply command line args
    vm_cli.vm_host = args.host
    vm_cli.vm_port = args.port
    vm_cli.vm_timeout = args.timeout
    # run tool
    try:
        # start cli loop or just a one shot run (command set at cmd line)
        if not args.command:
            vm_cli.cmdloop()
        else:
            # convert list of args -> command line
            cmd_line = ' '.join(args.command)
            vm_cli.onecmd(cmd_line)
    except KeyboardInterrupt:
        sys.exit(0)
